
CREATE TABLE `GROCERY`(
    `id` INT(6) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(128) NOT NULL,
    `type_id` INT(6) DEFAULT NULL,
    `bought` ENUM('yes','no') DEFAULT 'no',
    PRIMARY KEY(`id`)
);

CREATE TABLE `TYPE`(
    `id` INT(6) NOT NULL AUTO_INCREMENT,
    `name` varchar(64) NOT NULL,
    PRIMARY KEY(`id`)
);

ALTER TABLE `GROCERY` ADD FOREIGN KEY(`type_id`) REFERENCES `TYPE`(`id`);

CREATE TABLE `U`(
    `id` INT(6) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(128) NOT NULL,
    `surname` VARCHAR(128) NOT NULL,
    `email` VARCHAR (256) NOT NULL,
    `disabled` TINYINT(1) DEFAULT 0,
    `reg_date` DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(`id`)
);

CREATE TABLE `C_U`(
    `id` INT(6) NOT NULL AUTO_INCREMENT,
    `user_id` INT(6) NOT NULL,
    `cod` VARCHAR(128) NOT NULL,
    PRIMARY KEY(`id`)
);
ALTER TABLE `C_U` ADD FOREIGN KEY(`user_id`) REFERENCES `U`(`id`);

